package com.example.crex.model.enums;

public enum BowlingStyle {

    RIGHT_ARM_FAST,
    LEFT_ARM_FAST,
    RIGHT_ARM_FAST_MEDIUM,
    LEFT_ARM_FAST_MEDIUM,
    RIGHT_ARM_MEDIUM_FAST,
    LEFT_ARM_MEDIUM_FAST,
    RIGHT_ARM_MEDIUM,
    LEFT_ARM_MEDIUM,
    RIGHT_ARM_OFF_SPIN,
    LEFT_ARM_ORTHODOX_SPIN,
    RIGHT_ARM_LEG_SPIN,
    LEFT_ARM_UNORTHODOX_SPIN,
    RIGHT_ARM_GOOGLEY,
    LEFT_ARM_GOOGLEY,
    RIGHT_ARM_DOOSRA,
    RIGHT_ARM_TOP_SPIN,
    RIGHT_ARM_FLIPPER,
    LEFT_ARM_WRIST_SPIN


}
